name: news_app
description: A simple Flutter news app using NewsAPI.org
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
